language: python
python:
  - '2.7'
env:
  - DJANGO_DB_NAME='sana_test' DJANGO_DB_USER='test_db_user' DJANGO_DB_PASSWORD='test_db_password'
services:
  - postgresql
addons:
  postgresql: '9.3'
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
before_script:
  - createuser --superuser test_db_user -U postgres
  - psql -c "ALTER USER test_db_user WITH PASSWORD 'test_db_password';" -U postgres
  - psql -c 'create database sana_test;' -U postgres
script:
  - fab verify
after_success:
  - bash -x ./scripts/deploy.sh
notifications:
  slack:
    secure: a1bQgFl5K8+T6q89xg2hQI2ltsDeDQK8Xh09vCHcpM88bRtjcFkPBYB51GVuRQOuvLGVzFMFSHJrHNsZULo5qwRo7sgSyMkGiJ1kwF59SBZvKVEEdqPcQryLZaS7MLSN3bQfb48uRV17xwhbJCbVy/i9pIXIgzuFBEM1+Vd8H84=
