# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_element_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
